### ISSUE TITLE
Backend code relooping

### ISSUE THREAD

**Issue by VersaceXcodes** [raidendotai/cofounder#11]
The backend code generation keeps relooping after finishing:

log:complete: node:op:PROJECT::STATE:UPDATE	{"context":{"streams":{},"project":"todos"},"response":{"success":false},"data":{"operation":{"id":"backend:specifications:openapi"},"type":"end","con
log:complete: node:BACKEND:OPENAPI::DEFINE	{"context":{"streams":{},"project":"todos"},"response":{"backend":{"requirements":{"restApi":{"justifyYourAnswer":"A REST API is necessary for the Tod
log:done:   sequence:seq:project:init:v1:step:7/14	{"context":{"streams":{},"project":"todos"},"data":{"pm":{"details":{"text":"Project 'todos' :\nsimple to do web app","attachments":[],"design":{"aest
log:start:  sequence:seq:project:init:v1:step:8/14	{"context":{"streams":{},"project":"todos"},"data":{"pm":{"details":{"text":"Project 'todos' :\nsimple to do web app","attachments":[],"design":{"aest
log:enqueue:  node:BACKEND:SERVER::GENERATE	{"context":{"streams":{},"project":"todos"},"data":{"pm":{"details":{"text":"Project 'todos' :\nsimple to do web app","attachments":[],"design":{"aest
log:start:    node:BACKEND:SERVER::GENERATE	{"context":{"streams":{},"project":"todos"},"data":{"pm":{"details":{"text":"Project 'todos' :\nsimple to do web app","attachments":[],"design":{"aest
log:enqueue:  node:op:LLM::GEN	{"context":{"streams":{},"project":"todos","operation":{"key":"backend.server.main","meta":{"name":"Backend code","desc":"backend server main"}}},"dat
log:start:    node:op:LLM::GEN	{"context":{"streams":{},"project":"todos","operation":{"key":"backend.server.main","meta":{"name":"Backend code","desc":"backend server main"}}},"dat
log:complete: node:op:LLM::GEN	{"context":{"streams":{},"project":"todos","operation":{"key":"backend.server.main","meta":{"name":"Backend code","desc":"backend server main"}}},"res
**{
  asyncretry_error: {
    id: 'BACKEND:SERVER::GENERATE',
    error: Error: backend:server:generate error - generated is empty
        at Object.backendServerGenerate [as BACKEND:SERVER::GENERATE] (file:///Users/moel/cofounder/api/system/functions/backend/server.js:314:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async file:///Users/moel/cofounder/api/build.js:87:30
        at async file:///Users/moel/cofounder/api/build.js:84:25
        at async file:///Users/moel/cofounder/api/node_modules/p-queue/dist/index.js:187:36
  }
}**
log:enqueue:  node:op:LLM::GEN	{"context":{"streams":{},"project":"todos","operation":{"key":"backend.server.main","meta":{"name":"Backend code","desc":"backend server main"}}},"dat
log:start:    node:op:LLM::GEN	{"context":{"streams":{},"project":"todos","operation":{"key":"backend.server.main","meta":{"name":"Backend code","desc":"backend server main"}}},"dat

**Comment by LLMFocus** [comment]
same here , also have Backend code relooping

{
  asyncretry_error: {
    id: 'PM:UXDMD::ANALYSIS',
    error: TypeError: Cannot read properties of undefined (reading 'main')
        at Object.pmUxdmdAnalysis [as PM:UXDMD::ANALYSIS] (file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/system/functions/pm/uxdmd.js:154:33)
        at file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/build.js:87:56
        at RetryOperation.runAttempt [as _fn] (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\async-retry\lib\index.js:42:15)
        at RetryOperation.attempt (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\retry\lib\retry_operation.js:116:8)
        at run (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\async-retry\lib\index.js:55:8)
        at new Promise (<anonymous>)
        at retry (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\async-retry\lib\index.js:58:10)
        at file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/build.js:84:31
        at file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/node_modules/p-queue/dist/index.js:180:37
        at #tryToStartAnother (file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/node_modules/p-queue/dist/index.js:118:17)
  }
}
{
  asyncretry_error: {
    id: 'PM:UXDMD::ANALYSIS',
    error: TypeError: Cannot read properties of undefined (reading 'main')
        at Object.pmUxdmdAnalysis [as PM:UXDMD::ANALYSIS] (file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/system/functions/pm/uxdmd.js:154:33)
        at file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/build.js:87:56
        at RetryOperation.runAttempt [as _fn] (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\async-retry\lib\index.js:42:15)
        at Timeout._onTimeout (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\retry\lib\retry_operation.js:85:10)
        at listOnTimeout (node:internal/timers:573:17)
        at process.processTimers (node:internal/timers:514:7)
  }
}
{
  asyncretry_error: {
    id: 'PM:UXDMD::ANALYSIS',
    error: TypeError: Cannot read properties of undefined (reading 'main')
        at Object.pmUxdmdAnalysis [as PM:UXDMD::ANALYSIS] (file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/system/functions/pm/uxdmd.js:154:33)
        at file:///C:/AiWork/Code/Tool/cofounder/cofounder/api/build.js:87:56
        at RetryOperation.runAttempt [as _fn] (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\async-retry\lib\index.js:42:15)
        at Timeout._onTimeout (C:\AiWork\Code\Tool\cofounder\cofounder\api\node_modules\retry\lib\retry_operation.js:85:10)
        at listOnTimeout (node:internal/timers:573:17)
        at process.processTimers (node:internal/timers:514:7)

**Comment by zenics** [comment]
same on mine

**Comment by LLMFocus** [comment]
even after willchrisjr merge, i still have the same backend loop issue.

**Comment by rvanderson** [comment]
Same issue here, also after the merge.

**Comment by raidendotai** [comment]
- probably yaml parsing from the generated text ; typically when hits output token limits before it finishes the full code
- o1-preview limits lifts this , so will use it instead of claude 3.5 sonnet for architecture and long api passes in next versions

thanks

**Comment by ywd727** [comment]
> * 可能是从生成的文本中进行 yaml 解析；通常在完成整个代码之前达到输出标记限制
> * o1-preview 限制解除了这一点，因此将在下一版本中使用它代替 claude 3.5 sonnet 进行架构和长 api 传递
> 
> 谢谢

Hello, when will the next version be updated?
