### ISSUE TITLE
Asyncretry_error > Message overloaded

### ISSUE THREAD

**Issue by ftstp** [raidendotai/cofounder#3]
I start to see some of these (maybe one or 2) 

`{
  asyncretry_error: {
    id: 'op:LLM::GEN',
    error: APIConnectionError: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"} }
        at APIError.generate (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/error.mjs:33:20)
        at Stream.iterator (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/streaming.mjs:49:40)
        ... 5 lines matching cause stack trace ...
        at async file:///F:/apps/cofounder/cofounder/api/node_modules/p-queue/dist/index.js:187:36 {
      status: undefined,
      headers: undefined,
      request_id: undefined,
      error: undefined,
      cause: Error: SSE Error: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"} }
          at castToError (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/core.mjs:695:12)
          at APIError.generate (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/error.mjs:33:61)
          at Stream.iterator (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/streaming.mjs:49:40)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async inference (file:///F:/apps/cofounder/cofounder/api/utils/anthropic.js:88:19)
          at async Object.opLlmGen [as op:LLM::GEN] (file:///F:/apps/cofounder/cofounder/api/system/functions/op/llm.js:66:26)
          at async file:///F:/apps/cofounder/cofounder/api/build.js:87:30
          at async file:///F:/apps/cofounder/cofounder/api/build.js:84:25
          at async file:///F:/apps/cofounder/cofounder/api/node_modules/p-queue/dist/index.js:187:36
    }
  }
}
`

and after building another component it displays this:

`log:enqueue:  node:op:LLM::GEN  {"context":{"streams":{},"project":"nightly","operation":{"key":"_pm.brd.requirements","meta":{"name":"BRD Prepass","desc":"backend structure requirem
log:start:    node:op:LLM::GEN  {"context":{"streams":{},"project":"nightly","operation":{"key":"_pm.brd.requirements","meta":{"name":"BRD Prepass","desc":"backend structure requirem
log:complete: node:op:LLM::GEN  {"context":{"streams":{},"project":"nightly","operation":{"key":"_pm.brd.requirements","meta":{"name":"BRD Prepass","desc":"backend structure requirem
log:enqueue:  node:op:LLM::GEN  {"context":{"streams":{},"project":"nightly","operation":{"key":"pm.brd","meta":{"name":"BRD","desc":"backend requirements document"}}},"data":{"model
log:start:    node:op:LLM::GEN  {"context":{"streams":{},"project":"nightly","operation":{"key":"pm.brd","meta":{"name":"BRD","desc":"backend requirements document"}}},"data":{"model
{
  asyncretry_error: {
    id: 'op:LLM::GEN',
    error: APIConnectionError: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"}            }
        at APIError.generate (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/error.mjs:33:20)
        at Stream.iterator (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/streaming.mjs:49:40)
        ... 5 lines matching cause stack trace ...
        at async file:///F:/apps/cofounder/cofounder/api/node_modules/p-queue/dist/index.js:187:36 {
      status: undefined,
      headers: undefined,
      request_id: undefined,
      error: undefined,
      cause: Error: SSE Error: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"}            }
          at castToError (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/core.mjs:695:12)
          at APIError.generate (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/error.mjs:33:61)
          at Stream.iterator (file:///F:/apps/cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/streaming.mjs:49:40)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async inference (file:///F:/apps/cofounder/cofounder/api/utils/anthropic.js:88:19)
          at async Object.opLlmGen [as op:LLM::GEN] (file:///F:/apps/cofounder/cofounder/api/system/functions/op/llm.js:66:26)
          at async file:///F:/apps/cofounder/cofounder/api/build.js:87:30
          at async file:///F:/apps/cofounder/cofounder/api/build.js:84:25
          at async file:///F:/apps/cofounder/cofounder/api/node_modules/p-queue/dist/index.js:187:36
    }
  }
}`

Impossible to finish the completion since the last component is stuck for ever.

**Comment by raidendotai** [comment]
[`529 - overloaded_error: Anthropic’s API is temporarily overloaded`](https://docs.anthropic.com/en/api/errors)

come on it's right there in the logs
