### ISSUE TITLE
UI Generation not Completing - backend:server:generate error - generated is empty after 5 attempts

### ISSUE THREAD

**Issue by TheMarcusLee** [raidendotai/cofounder#33]
Same issue here. Always during the UI/UX generation. 

Console Output after the Operation Streams stop:
backend:server:generate error - generated is empty after 5 attempts
log:complete: node:op:PROJECT::STATE:UPDATE	{"context":{"streams":{},"project":"aiprojectname","sequence":{"resume":14}},"response":{"success":false},"data":{"operation":{"id":"settings:config:pa
log:complete: node:WEBAPP:VIEW::GENERATE	{"context":{"streams":{},"project":"aiprojectname","sequence":{"resume":14}},"response":{"webapp":{"react":{"root":{"app":{"1730511152372":{"analysis":
log:complete: node:WEBAPP:VIEW::GENERATE:MULTI	{"context":{"streams":{},"project":"aiprojectname","sequence":{"resume":14}},"response":{"webapp":{"react":{"root":{"app":{"1730511152372":{"analysis":
log:done:   sequence:seq:project:init:v1:step:14/14	{"context":{"streams":{},"project":"aiprojectname","sequence":{"resume":14}},"data":{"uxdatamap":{"structure":{"root":{"globalState":{"user":{"schema":
log:done:   sequence:seq:project:init:v1	{"context":{"streams":{},"project":"aiprojectname","sequence":{"resume":14}},"data":{"uxdatamap":{"structure":{"root":{"globalState":{"user":{"schema":

<img width="726" alt="image" src="https://github.com/user-attachments/assets/f8c88651-c980-40e1-8200-4c3c08e2fc60">

**Comment by aftabmj** [comment]
Same issue. The UI nodes are visible, but no code is updated in the vitereact folder. After a long time, the process restarts (blue notes disappear and start over generation). I am not even seeing UI screenshots like yours.

![image](https://github.com/user-attachments/assets/9d89c0f6-d704-45f7-81dd-ab1663ba0698)

on the cofounder/api CLI I see many messages like this :
{
  asyncretry_error: {
    id: 'op:LLM::GEN',
    error: BadRequestError: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}
        at APIError.generate (file:///home/amj/dev/exp_cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/error.mjs:37:20)
        at Anthropic.makeStatusError (file:///home/amj/dev/exp_cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/core.mjs:268:25)
        at Anthropic.makeRequest (file:///home/amj/dev/exp_cofounder/cofounder/api/node_modules/@anthropic-ai/sdk/core.mjs:311:30)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async inference (file:///home/amj/dev/exp_cofounder/cofounder/api/utils/anthropic.js:74:20)
        at async Object.opLlmGen [as op:LLM::GEN] (file:///home/amj/dev/exp_cofounder/cofounder/api/system/functions/op/llm.js:66:26)
        at async file:///home/amj/dev/exp_cofounder/cofounder/api/build.js:87:30
        at async file:///home/amj/dev/exp_cofounder/cofounder/api/build.js:84:25
        at async file:///home/amj/dev/exp_cofounder/cofounder/api/node_modules/p-queue/dist/index.js:187:36 {
      status: 400,
      headers: {
        'cf-cache-status': 'DYNAMIC',
        'cf-ray': '8dca6598f922d9a8-AKL',
        connection: 'keep-alive',
        'content-length': '117',
        'content-type': 'application/json',
        date: 'Sun, 03 Nov 2024 06:44:38 GMT',
        'request-id': 'req_01Gc84pdzPJPdHcsKrwKJrXk',
        server: 'cloudflare',
        via: '1.1 google',
        'x-robots-tag': 'none',
        'x-should-retry': 'false'
      },
      request_id: 'req_01Gc84pdzPJPdHcsKrwKJrXk',
      error: {
        type: 'error',
        error: {
          type: 'invalid_request_error',
          message: 'messages: text content blocks must be non-empty'
        }
      }
    }
  }
}

My prompt was to generate the most basic To Do app. I have not yet been successful because of the above issue.
Many thanks !

**Comment by BioCruz-sudo** [comment]
I'm getting the exact same error when waiting for my API limits to refresh and then trying again it just hangs on these UV_ components and when I try to wait again for my limits to reset and resume it just does it again.

**Comment by raidendotai** [comment]
- yea , each view typically run in 4 passes ( functional pass , design analysis pass , design generation pass , apply design changes pass ) , should have more logs intermittently rather than first only
- seems to get mockup design right often , which is good

- the ui->code part is a temporary bridge ; the vision is to have generative design systems to cover the whole project. still working on and training ui models so we'll see what comes out of that :)
