### ISSUE TITLE
 looping on building database 

### ISSUE THREAD

**Issue by SAHARINTP** [raidendotai/cofounder#62]
the platform is looping for me on creating the database code ande keeps making the same thing with some bugs coming up on the terminal :

 asyncretry_error: {
    id: 'BACKEND:SERVER::GENERATE',
    error: Error: backend:server:generate error - generated is empty
        at Object.backendServerGenerate [as BACKEND:SERVER::GENERATE] (file:///home/intp/cofounder/api/system/functions/backend/server.js:314:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async file:///home/intp/cofounder/api/build.js:87:30
        at async file:///home/intp/cofounder/api/build.js:84:25
        at async file:///home/intp/cofounder/api/node_modules/p-queue/dist/index.js:187:36
        
        and this : 
        
          asyncretry_error: {
    id: 'WEBAPP:VIEW::GENERATE',
    error: TypeError: Cannot read properties of undefined (reading 'views')
        at Object.webappViewGenerate [as WEBAPP:VIEW::GENERATE] (file:///home/intp/cofounder/api/system/functions/webapp/view.js:490:27)
        at file:///home/intp/cofounder/api/build.js:87:56
        at RetryOperation.runAttempt [as _fn] (/home/intp/cofounder/api/node_modules/async-retry/lib/index.js:42:15)
        at Timeout._onTimeout (/home/intp/cofounder/api/node_modules/retry/lib/retry_operation.js:85:10)
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7)
  }
}
{
  SYSTEM_RUN_ERR: {
    err: Error: TypeError: Cannot read properties of undefined (reading 'views')
        at file:///home/intp/cofounder/api/build.js:107:17
        at async file:///home/intp/cofounder/api/build.js:84:25
        at async file:///home/intp/cofounder/api/node_modules/p-queue/dist/index.js:187:36,
    id: 'WEBAPP:VIEW::GENERATE'

can anyone lead me in the right direction?.?

**Comment by suediedev** [comment]
You saw the README. It is a alpha version wait intil v1 is released
