### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:667

### ISSUE THREAD

**Issue by zaakirio** [raidendotai/cofounder#67]
I receive the following error when attempting to create a project.
Steps to replicate:
1. Clone repository
2.  Run `npx @openinterface/cofounder`

Error:
```
{
  build: {
    'BACKEND:ASYNCAPI::DEFINE': [AsyncFunction: backendAsyncapiDefine],
    'BACKEND:OPENAPI::DEFINE': [AsyncFunction: backendOpenapiDefine],
    'BACKEND:SERVER::GENERATE': [AsyncFunction: backendServerGenerate],
    'DB:POSTGRES::GENERATE': [AsyncFunction: dbPostgresGenerate],
    'DB:SCHEMAS::GENERATE': [AsyncFunction: dbSchemasGenerate],
    'DESIGNER:LAYOUTV1::VIEW:GENERATE': [AsyncFunction: designerLayoutv1ViewGenerate],
    'DESIGNER:LAYOUTV1::VIEW:ITERATE': [AsyncFunction: designerLayoutv1ViewIterate],
    'op:CONVERT::MARKDOWN:PDF': [AsyncFunction: opConvertMarkdownPdf],
    'op:INDEXDB::QUERY': [AsyncFunction: opIndexdbQuery],
    'op:LLM::GEN': [AsyncFunction: opLlmGen],
    'op:LLM::VECTORIZE': [AsyncFunction: opLlmVectorize],
    'op:LLM::VECTORIZE:CHUNK': [AsyncFunction: opLlmVectorizeChunk],
    'op:LLM::DEBUG:SIMULATE': [AsyncFunction: opLlmDebugSimulate],
    'op:PROJECT::STATE:UPDATE': [AsyncFunction: opProjectStateUpdate],
    'op:PROJECT::STATE:LOAD': [AsyncFunction: opProjectStateLoad],
    'op:PROJECT::STATE:SETUP': [AsyncFunction: opProjectStateSetup],
    'op:PROJECT::STATE:EXPORT': [AsyncFunction: opProjectStateExport],
    'op:RENDER::LAYOUT': [AsyncFunction: opRenderLayout],
    'PM:BRD::ANALYSIS': [AsyncFunction: pmBrdAnalysis],
    'PM:DRD::ANALYSIS': [AsyncFunction: pmDrdAnalysis],
    'PM:FJMD::ANALYSIS': [AsyncFunction: pmFjmdAnalysis],
    'PM:FRD::ANALYSIS': [AsyncFunction: pmFrdAnalysis],
    'PM:PRD::ANALYSIS': [AsyncFunction: pmPrdAnalysis],
    'PM:UXDMD::ANALYSIS': [AsyncFunction: pmUxdmdAnalysis],
    'PM:UXSMD::ANALYSIS': [AsyncFunction: pmUxsmdAnalysis],
    'SWARM:AUGMENT::BACKEND:EXTERNALAPIS': [AsyncFunction: swarmAugmentBackendExternalapis],
    'SWARM:FIX::BACKEND': [AsyncFunction: swarmFixBackend],
    'SWARM:FIX::WEBAPP': [AsyncFunction: swarmFixWebapp],
    'SWARM:REVIEW::SERVER:MAIN': [AsyncFunction: swarmReviewServerMain],
    'SWARM:REVIEW::WEBAPP:STORE': [AsyncFunction: swarmReviewWebappStore],
    'SWARM:REVIEW::WEBAPP:ROOT': [AsyncFunction: swarmReviewWebappRoot],
    'SWARM:REVIEW::WEBAPP:VIEW': [AsyncFunction: swarmReviewWebappView],
    'UX:DATAMAP::STRUCTURE': [AsyncFunction: uxDatamapStructure],
    'UX:DATAMAP::VIEWS': [AsyncFunction: uxDatamapViews],
    'UX:DATAMAP::VIEWS:CHUNK': [AsyncFunction: uxDatamapViewsChunk],
    'UX:SITEMAP::STRUCTURE': [AsyncFunction: uxSitemapStructure],
    'UX:SITEMAP::VIEWS': [AsyncFunction: uxSitemapViews],
    'UX:SITEMAP::VIEWS:NORMAL': [AsyncFunction: uxSitemapViewsNormal],
    'UX:SITEMAP::VIEWS:SPECIAL': [AsyncFunction: uxSitemapViewsSpecial],
    'UX:SITEMAP::VIEWS:SHARED': [AsyncFunction: uxSitemapViewsShared],
    'WEBAPP:ROOT::GENERATE': [AsyncFunction: webappRootGenerate],
    'WEBAPP:STORE::GENERATE': [AsyncFunction: webappStoreGenerate],
    'WEBAPP:VIEW::GENERATE:MULTI': [AsyncFunction: webappViewGenerateMulti],
    'WEBAPP:VIEW::GENERATE': [AsyncFunction: webappViewGenerate],
    'WEBAPP:VIEW::ITERATE': [AsyncFunction: webappViewIterate]
  }
}
build:DAG : parent node WEBAPP:STORE::GENERATE of node WEBAPP:ROOT::GENERATE not found in DAG - skipping dependency
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:667
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at Function.listen (/home/user/Experiments/Cofounder/cofounder/api/node_modules/express/lib/application.js:635:24)
    at file:///home/user/Experiments/Cofounder/cofounder/api/server.js:134:20
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 667
}

Node.js v18.20.4
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by suediedev** [comment]
Run the script with root

**Comment by raidendotai** [comment]
ports fixed
